#! /bin/bash
# del - This simple command allows the user to delete a file by typing in del followed by the file name
# Emaz Khan 12/11/2018

#This makes sure that the file exists and that the input is not blank
if [[ -e $1 ]] && [[ -n $# ]]; then

echo "File has been deleted"

cp -r $1 $HOME/.waste
rm $1
else
	echo "File does not exist"
fi
