#! /bin/bash
# emptywaste - This simple command empties the waste file that stores all the deleted file, the waste file can be found at the home directory
# Emaz Khan 12/11/2018

#This is the command for deletting everything in the .waste folder one by one
rm $HOME/.waste/*
echo "Waste emptied"
